import Vue from 'vue'
import Vuex from 'vuex'
Vue.use(Vuex)
export const store =new Vuex.Store({
    state:{
        sliders:{},
        comments:{},
        partners:{},
        events:{},
        videos:{},
        images:{},
    },
    mutations:{
        loadSliders(state,data){
            state.sliders=data
        },
        loadComments(state,data){
            state.comments=data
        },
        loadPartners(state,data){
            state.partners=data
        },
        loadEvents(state,data){
            state.events=data
        },
        loadVideos(state,data){
            state.videos=data
        },
        loadImages(state,data){
            state.images=data
        },
    },
    actions:{
        loadSliders(context){
            axios.get(BACKEND_ENDPOINT+'api/sliders').then(({data})=>{
                context.commit('loadSliders',data)
            }).catch(error=>{
                console.log(error)
            })
        },
        loadComments(context){
            axios.get(BACKEND_ENDPOINT+'api/comments').then(({data})=>{
                context.commit('loadComments',data)
            }).catch(error=>{
                console.log(error)
            })
        },
        loadPartners(context){
            axios.get(BACKEND_ENDPOINT+'api/partners').then(({data})=>{
                context.commit('loadPartners',data)
            }).catch(error=>{
                console.log(error)
            })
        },
        loadEvents(context){
            axios.get(BACKEND_ENDPOINT+'api/events').then(({data})=>{
                context.commit('loadEvents',data)
            }).catch(error=>{
                console.log(error)
            })
        },
        loadVideos(context){
            axios.get(BACKEND_ENDPOINT+'api/videos').then(({data})=>{
                context.commit('loadVideos',data)
            }).catch(error=>{
                console.log(error)
            })
        },
        loadImages(context){
            axios.get(BACKEND_ENDPOINT+'api/images').then(({data})=>{
                context.commit('loadImages',data)
            }).catch(error=>{
                console.log(error)
            })
        },

    }
})